apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  config.yaml: |-
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 5s
              static_configs:
                - targets: ['prometheus-kube-state-metrics.default.svc:8080','prometheus-prometheus-node-exporter.default.svc:9100','event-exporter.default.svc:9102']
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55680
          http:
            endpoint: 0.0.0.0:55681
    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
      metricstransform:
        transforms:
          include: .+
          match_type: regexp
          action: update
          operations:
            - action: update_label
              label: namespace
              new_label: k8s.namespace.name
            - action: add_label
              new_label: dt.kubernetes.config.id
              new_value: DYNATRACE_CLUSTER_ID
            - action: update_label
              label: uid
              new_label: k8s.pod.uid
            - action: update_label
              label: system_uuid
              new_label: dt.kubernetes.node.system_uuid
    exporters:
      otlphttp:
        endpoint: "TENANTURL_TOREPLACE/api/v2/otlp"
        headers: {"Authorization": "Api-Token DT_API_TOKEN_TO_REPLACE"}
      logging:
        loglevel: debug
        sampling_initial: 5
        sampling_thereafter: 200
      prometheus:
         endpoint: "0.0.0.0:9091"
      dynatrace:
       # optional - Dimensions specified here will be included as a dimension on every exported metric
       #            unless that metric already has a dimension with the same key.
       # optional - prefix will be prepended to each metric name in prefix.name format
       prefix: otpcol
       endpoint: "TENANTURL_TOREPLACE/api/v2/metrics/ingest"
       # Token must at least have the Ingest metrics (metrics.ingest) permission
       api_token: "DT_API_TOKEN_TO_REPLACE"
    service:
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: []
          exporters: [otlphttp]
        metrics:
          receivers: [prometheus]
          processors: [metricstransform,batch]
          exporters: [dynatrace]
---
apiVersion: v1
kind: Service
metadata:
  name: otlp-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: otlp # Default endpoint for OpenTelemetry receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: jaeger-grpc # Default endpoint for Jaeger gRPC receiver
      port: 14250
    - name: prometheus-http # Default endpoint for Jaeger HTTP receiver.
      port: 9091
    - name: jaeger-thrift-http # Default endpoint for Jaeger HTTP receiver.
      port: 14268
    - name: zipkin # Default endpoint for Zipkin receiver.
      port: 9411
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
    - port: 55680
      name: kspan
      protocol: TCP
      targetPort: 55680
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.22.0
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - mountPath: /var/log
            name: varlog
            readOnly: true
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true
          - mountPath: /etc/otel/config.yaml
            name: data
            subPath: config.yaml
            readOnly: true
        ports:
          - containerPort: 55679 # Default endpoint for ZPages.
          - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
          - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
          - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
          - containerPort: 9411 # Default endpoint for Zipkin receiver.
          - containerPort: 8888  # Default endpoint for querying metrics.
          - containerPort: 55680
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        configMap:
          name: otel-collector-conf


